IMPORTING IMPORTANT PACKAGES


In [283]:
import pandas as pd
import numpy as np 
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from random import seed
from random import randrange
from csv import reader
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn import datasets, metrics, model_selection
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [59]:
pwd

'C:\\Users\\Utkarsh'

SINCE THE DATA HAS BEEN CHANGED, WE USED THE NEW DATASET WHICH IS NAMED AS SOYABEAN_new.csv


In [270]:
df=pd.read_csv('SOYABEAN_new.csv',names=col_names,header= None)
df.head()
y=df['class']
x=df.drop(['class'],axis=1)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      1.0
11      1.0
12      1.0
13      1.0
14      1.0
15      1.0
16      1.0
17      1.0
18      1.0
19      1.0
20      2.0
21      2.0
22      2.0
23      2.0
24      2.0
25      2.0
26      2.0
27      2.0
28      2.0
29      2.0
       ... 
277    14.0
278    14.0
279    14.0
280    14.0
281    14.0
282    14.0
283    14.0
284    14.0
285    14.0
286    14.0
287    14.0
288    14.0
289    14.0
290    15.0
291    15.0
292    15.0
293    15.0
294    15.0
295    15.0
296    16.0
297    16.0
298    16.0
299    16.0
300    16.0
301    16.0
302    17.0
303    18.0
304    18.0
305    18.0
306    18.0
Name: class, Length: 307, dtype: float64

Now, giving the column names to the columns in the dataset but the columns which had less correlation with the outut variable are dropped

In [183]:
col_names=['date','plant stand','precip', 'temp','hail','area damage','severity','plant growth','halo','marg','size','leaf mild','stem','lodging','int discolor','sclerotia','fruit pods','fruit spots','seed','mold growth','seed discolor','seed size','shriveling','class']

In [184]:
df1 = pd.read_csv('SOYABEAN_new.csv', header=None, names=col_names)

In [175]:
df1.head()

date  plant stand  precip  temp  hail  area damage  severity  plant growth  \
0   6.0          0.0     2.0   1.0   0.0          1.0       1.0           1.0   
1   4.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
2   3.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
3   3.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
4   6.0          0.0     2.0   1.0   0.0          0.0       1.0           1.0   

   halo  marg  ...    int discolor  sclerotia  fruit pods  fruit spots  seed  \
0   0.0   2.0  ...             0.0        0.0         4.0          0.0   0.0   
1   0.0   2.0  ...             0.0        0.0         4.0          0.0   0.0   
2   0.0   2.0  ...             0.0        0.0         4.0          0.0   0.0   
3   0.0   2.0  ...             0.0        0.0         4.0          0.0   0.0   
4   0.0   2.0  ...             0.0        0.0         4.0          0.0   0.0   

   mold growth  seed discolor  seed size  shriveling  class  
0          0.0            0.0        0.0         0.0    NaN  
1          0.0            0.0        0.0         0.0    NaN  
2          0.0            0.0        0.0         0.0    NaN  
3          0.0            0.0        0.0         0.0    NaN  
4          0.0            0.0        0.0         0.0    NaN  

[5 rows x 27 columns]

In [64]:
(df1.isnull()==True).count()

date               1372
plant stand        1372
precip             1372
temp               1372
hail               1372
crop hist          1372
area damage        1372
severity           1372
seed tmt           1372
germination        1372
plant growth       1372
leaves             1372
halo               1372
marg               1372
size               1372
leaf shred         1372
leaf malf          1372
leaf mild          1372
stem               1372
lodging            1372
stem cankers       1372
canker lesion      1372
fruiting bodies    1372
external decay     1372
mycelium           1372
int discolor       1372
sclerotia          1372
fruit pods         1372
fruit spots        1372
seed               1372
mold growth        1372
seed discolor      1372
seed size          1372
shriveling         1372
roots              1372
class              1372
dtype: int64

In [65]:
df1['date'].value_counts()

 0.570600    5
 0.329200    4
 0.379800    4
 0.519500    4
-2.647900    3
-1.300000    3
-1.858400    3
 0.929700    3
-0.206200    3
 0.600500    2
-0.048008    2
 4.021500    2
-0.873400    2
-0.278000    2
-1.341400    2
 4.055200    2
-2.314200    2
-0.959230    2
-0.786900    2
 2.015300    2
-0.718680    1
 4.296900    1
 4.890600    1
-0.973250    1
-0.266540    1
 4.429500    1
-5.204900    1
 4.649900    1
 1.684900    1
-0.360380    1
            ..
-2.336100    1
-2.564000    1
-1.778100    1
-3.959400    1
-0.556480    1
 6.091900    1
 0.751080    1
-0.001285    1
-3.895200    1
 1.063700    1
-1.242400    1
 0.224320    1
 4.247800    1
 2.452700    1
 2.254600    1
 3.971900    1
-0.720680    1
 0.642150    1
 0.115920    1
 0.335650    1
 2.313600    1
 4.934200    1
-0.942550    1
-0.416450    1
 4.468200    1
 3.269700    1
-0.568770    1
-4.366700    1
 4.650000    1
-3.312500    1
Name: date, Length: 1338, dtype: int64

In [66]:
df1['plant stand'].value_counts()

-4.455200     6
-3.263300     5
 0.709800     4
-0.024800     4
-3.797100     4
 9.220700     3
 9.566300     3
 8.188100     3
 7.886000     3
 0.039307     3
 9.293100     3
 10.137400    3
 10.267800    3
 9.156600     2
 0.235890     2
-6.841000     2
-0.244180     2
 8.384700     2
 0.662160     2
 9.086200     2
 9.181400     2
 3.267400     2
 6.118900     2
 8.008100     2
-6.882400     2
 6.625800     2
-0.155210     2
-0.146930     2
 0.124150     2
 3.192900     2
             ..
-7.250800     1
 11.296200    1
 8.641300     1
 7.662500     1
-1.409200     1
-0.357990     1
 1.845800     1
 1.854100     1
 0.558700     1
 3.335700     1
 9.009600     1
 2.290700     1
 1.092600     1
 4.550300     1
 5.268400     1
-4.556600     1
-10.451900    1
-6.880400     1
 5.758800     1
 8.732400     1
 1.036700     1
 3.418400     1
-10.524400    1
 2.994200     1
 9.460700     1
-7.832200     1
 2.907300     1
 3.325300     1
 2.143800     1
 0.802870     1
Name: plant stand, Lengt

Whether the data has any null values in the class column?

In [67]:
df1['class'].isnull()==True

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
        ... 
1342    True
1343    True
1344    True
1345    True
1346    True
1347    True
1348    True
1349    True
1350    True
1351    True
1352    True
1353    True
1354    True
1355    True
1356    True
1357    True
1358    True
1359    True
1360    True
1361    True
1362    True
1363    True
1364    True
1365    True
1366    True
1367    True
1368    True
1369    True
1370    True
1371    True
Name: class, Length: 1372, dtype: bool

In [68]:
df1['class'].value_counts()

Series([], Name: class, dtype: int64)

In [201]:
df1.describe()

date  plant stand      precip        temp        hail  \
count  307.000000   307.000000  307.000000  307.000000  307.000000   
mean     3.534202     0.459283    1.592834    1.127036    0.179153   
std      1.711544     0.505658    0.705034    0.615820    0.384107   
min      0.000000     0.000000    0.000000    0.000000    0.000000   
25%      2.000000     0.000000    1.000000    1.000000    0.000000   
50%      4.000000     0.000000    2.000000    1.000000    0.000000   
75%      5.000000     1.000000    2.000000    2.000000    0.000000   
max      6.000000     2.000000    2.000000    2.000000    1.000000   

       area damage    severity  plant growth        halo        marg  \
count   307.000000  307.000000    307.000000  307.000000  307.000000   
mean      1.631922    0.885993      0.338762    1.130293    0.843648   
std       1.077711    0.664235      0.474062    0.961324    0.970976   
min       0.000000    0.000000      0.000000    0.000000    0.000000   
25%       1.000000    0.000000      0.000000    0.000000    0.000000   
50%       2.000000    1.000000      0.000000    2.000000    0.000000   
75%       3.000000    1.000000      1.000000    2.000000    2.000000   
max       3.000000    2.000000      1.000000    2.000000    2.000000   

          ...      int discolor   sclerotia  fruit pods  fruit spots  \
count     ...        307.000000  307.000000  307.000000   307.000000   
mean      ...          0.130293    0.032573    0.739414     1.273616   
std       ...          0.423139    0.177807    1.136376     1.694875   
min       ...          0.000000    0.000000    0.000000     0.000000   
25%       ...          0.000000    0.000000    0.000000     0.000000   
50%       ...          0.000000    0.000000    0.000000     0.000000   
75%       ...          0.000000    0.000000    1.000000     4.000000   
max       ...          2.000000    1.000000    3.000000     4.000000   

             seed  mold growth  seed discolor   seed size  shriveling  \
count  307.000000   307.000000     307.000000  307.000000  307.000000   
mean     0.166124     0.100977       0.091205    0.087948    0.052117   
std      0.372799     0.301790       0.288371    0.283681    0.222626   
min      0.000000     0.000000       0.000000    0.000000    0.000000   
25%      0.000000     0.000000       0.000000    0.000000    0.000000   
50%      0.000000     0.000000       0.000000    0.000000    0.000000   
75%      0.000000     0.000000       0.000000    0.000000    0.000000   
max      1.000000     1.000000       1.000000    1.000000    1.000000   

            class  
count  307.000000  
mean     8.420195  
std      4.753669  
min      0.000000  
25%      4.000000  
50%      8.000000  
75%     13.000000  
max     18.000000  

[8 rows x 24 columns]

In [202]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 24 columns):
date             307 non-null float64
plant stand      307 non-null float64
precip           307 non-null float64
temp             307 non-null float64
hail             307 non-null float64
area damage      307 non-null float64
severity         307 non-null float64
plant growth     307 non-null float64
halo             307 non-null float64
marg             307 non-null float64
size             307 non-null float64
leaf mild        307 non-null float64
stem             307 non-null float64
lodging          307 non-null float64
int discolor     307 non-null float64
sclerotia        307 non-null float64
fruit pods       307 non-null float64
fruit spots      307 non-null float64
seed             307 non-null float64
mold growth      307 non-null float64
seed discolor    307 non-null float64
seed size        307 non-null float64
shriveling       307 non-null float64
class            307 

In [203]:
df1.corr()

date  plant stand    precip      temp      hail  \
date           1.000000    -0.333507 -0.081855  0.279563 -0.036691   
plant stand   -0.333507     1.000000  0.113762 -0.062045 -0.105338   
precip        -0.081855     0.113762  1.000000  0.006620 -0.176256   
temp           0.279563    -0.062045  0.006620  1.000000  0.027811   
hail          -0.036691    -0.105338 -0.176256  0.027811  1.000000   
area damage    0.126436    -0.150526 -0.098964  0.193786  0.017718   
severity      -0.429178     0.263431  0.081989 -0.148230 -0.111815   
plant growth  -0.360708     0.248589 -0.055290 -0.170282  0.096341   
halo           0.150219    -0.184013  0.247288  0.220359 -0.081123   
marg          -0.144255     0.193328 -0.241285 -0.234475  0.084112   
size          -0.112386     0.209187 -0.173353 -0.124157 -0.035225   
leaf mild     -0.009864     0.086043 -0.044733 -0.159812  0.122033   
stem           0.022154     0.094566 -0.046487 -0.023562 -0.135046   
lodging        0.116715    -0.034800 -0.151100 -0.119220  0.353427   
int discolor   0.178835    -0.204227 -0.676028  0.049144  0.117301   
sclerotia      0.135927    -0.166938 -0.415232  0.141158  0.153524   
fruit pods    -0.398658     0.419391  0.250555 -0.158014 -0.147251   
fruit spots   -0.148562     0.264710 -0.056879 -0.099163 -0.010285   
seed           0.157522    -0.163364  0.183587 -0.063755  0.133809   
mold growth    0.078704    -0.005092  0.147787  0.001088  0.097156   
seed discolor  0.159190    -0.176153  0.086809  0.026555  0.176541   
seed size      0.118302    -0.077473  0.114270  0.066783 -0.055098   
shriveling     0.218298     0.018912  0.093998  0.142244 -0.071329   
class          0.319357    -0.178437  0.298885  0.251860 -0.129062   

               area damage  severity  plant growth      halo      marg  \
date              0.126436 -0.429178     -0.360708  0.150219 -0.144255   
plant stand      -0.150526  0.263431      0.248589 -0.184013  0.193328   
precip           -0.098964  0.081989     -0.055290  0.247288 -0.241285   
temp              0.193786 -0.148230     -0.170282  0.220359 -0.234475   
hail              0.017718 -0.111815      0.096341 -0.081123  0.084112   
area damage       1.000000 -0.127289     -0.228482  0.223084 -0.198832   
severity         -0.127289  1.000000      0.558935 -0.437267  0.453634   
plant growth     -0.228482  0.558935      1.000000 -0.563278  0.598218   
halo              0.223084 -0.437267     -0.563278  1.000000 -0.972406   
marg             -0.198832  0.453634      0.598218 -0.972406  1.000000   
size             -0.117485  0.479347      0.533553 -0.813365  0.840995   
leaf mild        -0.084721 -0.057451     -0.178631 -0.051216 -0.045563   
stem             -0.051854  0.434313      0.461897 -0.523053  0.560706   
lodging           0.008059  0.001090      0.231495 -0.178342  0.183278   
int discolor      0.177173  0.064650      0.235404 -0.298955  0.304274   
sclerotia         0.148043  0.031546      0.256362 -0.216098  0.218883   
fruit pods       -0.228007  0.557980      0.619372 -0.450447  0.481260   
fruit spots      -0.223785  0.588042      0.770932 -0.645732  0.659546   
seed              0.022547 -0.187211     -0.079085 -0.005881 -0.027319   
mold growth       0.064411 -0.023896     -0.125669 -0.045497 -0.001707   
seed discolor     0.066312 -0.235576     -0.083318  0.015936  0.004410   
seed size         0.084852 -0.015987     -0.003562  0.005777 -0.009236   
shriveling        0.107457 -0.025987     -0.136870 -0.062372  0.068055   
class             0.145109 -0.561257     -0.530323  0.662340 -0.630011   

                 ...     int discolor  sclerotia  fruit pods  fruit spots  \
date             ...         0.178835   0.135927   -0.398658    -0.148562   
plant stand      ...        -0.204227  -0.166938    0.419391     0.264710   
precip           ...        -0.676028  -0.415232    0.250555    -0.056879   
temp             ...         0.049144   0.141158   -0.158014    -0.099163   
hail             ...         0.1

In [204]:
df2=df1[df1['class']==0]
df2

date  plant stand  precip  temp  hail  area damage  severity  plant growth  \
0   6.0          0.0     2.0   1.0   0.0          1.0       1.0           1.0   
1   4.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
2   3.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
3   3.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   
4   6.0          0.0     2.0   1.0   0.0          0.0       1.0           1.0   
5   5.0          0.0     2.0   1.0   0.0          0.0       1.0           1.0   
6   5.0          0.0     2.0   1.0   0.0          0.0       1.0           1.0   
7   4.0          0.0     2.0   1.0   1.0          0.0       1.0           1.0   
8   6.0          0.0     2.0   1.0   0.0          0.0       1.0           1.0   
9   4.0          0.0     2.0   1.0   0.0          0.0       2.0           1.0   

   halo  marg  ...    int discolor  sclerotia  fruit pods  fruit spots  seed  \
0   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
1   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
2   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
3   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
4   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
5   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
6   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
7   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
8   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   
9   0.0   2.0  ...             0.0        0.0         0.0          4.0   0.0   

   mold growth  seed discolor  seed size  shriveling  class  
0          0.0            0.0        0.0         0.0    0.0  
1          0.0            0.0        0.0         0.0    0.0  
2          0.0            0.0        0.0         0.0    0.0  
3          0.0            0.0        0.0         0.0    0.0  
4          0.0            0.0        0.0         0.0    0.0  
5          0.0            0.0        0.0         0.0    0.0  
6          0.0            0.0        0.0         0.0    0.0  
7          0.0            0.0        0.0         0.0    0.0  
8          0.0            0.0        0.0         0.0    0.0  
9          0.0            0.0        0.0         0.0    0.0  

[10 rows x 24 columns]

In [205]:
df3=df1[df1['class']==1]
df3

date  plant stand  precip  temp  hail  area damage  severity  \
10   6.0          0.0     0.0   2.0   0.0          3.0       1.0   
11   4.0          0.0     0.0   1.0   1.0          3.0       1.0   
12   3.0          0.0     0.0   1.0   0.0          2.0       1.0   
13   6.0          0.0     0.0   1.0   1.0          3.0       1.0   
14   6.0          0.0     0.0   2.0   0.0          3.0       1.0   
15   5.0          0.0     0.0   2.0   1.0          3.0       1.0   
16   6.0          0.0     0.0   2.0   1.0          2.0       1.0   
17   4.0          0.0     0.0   1.0   0.0          2.0       1.0   
18   3.0          0.0     0.0   2.0   0.0          2.0       1.0   
19   5.0          0.0     0.0   2.0   1.0          2.0       1.0   

    plant growth  halo  marg  ...    int discolor  sclerotia  fruit pods  \
10           1.0   0.0   2.0  ...             2.0        1.0         0.0   
11           1.0   0.0   2.0  ...             2.0        1.0         0.0   
12           1.0   0.0   2.0  ...             2.0        1.0         0.0   
13           1.0   0.0   2.0  ...             2.0        1.0         0.0   
14           1.0   0.0   2.0  ...             2.0        1.0         0.0   
15           1.0   0.0   2.0  ...             2.0        1.0         0.0   
16           1.0   0.0   2.0  ...             2.0        1.0         0.0   
17           1.0   0.0   2.0  ...             2.0        1.0         0.0   
18           1.0   0.0   2.0  ...             2.0        1.0         0.0   
19           1.0   0.0   2.0  ...             2.0        1.0         0.0   

    fruit spots  seed  mold growth  seed discolor  seed size  shriveling  \
10          4.0   0.0          0.0            0.0        0.0         0.0   
11          4.0   0.0          0.0            0.0        0.0         0.0   
12          4.0   0.0          0.0            0.0        0.0         0.0   
13          4.0   0.0          0.0            0.0        0.0         0.0   
14          4.0   0.0          0.0            0.0        0.0         0.0   
15          4.0   0.0          0.0            0.0        0.0         0.0   
16          4.0   0.0          0.0            0.0        0.0         0.0   
17          4.0   0.0          0.0            0.0        0.0         0.0   
18          4.0   0.0          0.0            0.0        0.0         0.0   
19          4.0   0.0          0.0            0.0        0.0         0.0   

    class  
10    1.0  
11    1.0  
12    1.0  
13    1.0  
14    1.0  
15    1.0  
16    1.0  
17    1.0  
18    1.0  
19    1.0  

[10 rows x 24 columns]

NOW WE WILL PROCEED FURTHER TO SHOW YOU HOW WE REMOVED THE '?' SYMBOL WITH THE MODE OF THAT COLUMN

In [412]:
df4=df1[df1['class']==2]
df5=df1[df1['class']==3]
df6=df1[df1['class']==4]
df7=df1[df1['class']==5]
df8=df1[df1['class']==6]
df9=df1[df1['class']==7]
df10=df1[df1['class']==8]
df11=df1[df1['class']==9]
df12=df1[df1['class']==10]
df13=df1[df1['class']==11]
df14=df1[df1['class']==12]
df15=df1[df1['class']==13]
df16=df1[df1['class']==14]
df17=df1[df1['class']==15]
df18=df1[df1['class']==16]
df19=df1[df1['class']==17]
df20=df1[df1['class']==18]

In [413]:
df21=df2
df31=df3
df41=df4
df51=df5
df61=df6
df71=df7
df81=df8
df91=df9
df101=df10
df111=df11
df121=df12
df131=df13
df141=df14
df151=df15
df161=df16
df171=df17
df181=df18
df191=df19
df201=df20

In [414]:
np.sum(df5=='?')

date             0
plant stand      0
precip           0
temp             0
hail             0
area damage      0
severity         0
plant growth     0
halo             0
marg             0
size             0
leaf mild        0
stem             0
lodging          0
int discolor     0
sclerotia        0
fruit pods       0
fruit spots      0
seed             0
mold growth      0
seed discolor    0
seed size        0
shriveling       0
class            0
dtype: int64

In [209]:
import statistics

HERE THESE LINES TO FIND THE MODE AREN'T SUPPOSED TO BE RUN AND THAT IS BECAUSE IT DOES'NT HAVE ANY SIGNIFICANCE AFTER THE CHANGES WE DID ON THE DATASET AND WOULD GIVE AN ERROR IF RUN, WE REPLACED THE MISSING VALUES('?') BY THE MODE OF THE COLUMNS

In [415]:
statistics.mode(df5[df5['hail']!='?']['hail'])

In [416]:
statistics.mode(df5[df5['severity']!='?']['severity'])

In [417]:
statistics.mode(df5[df5['seed tmt']!='?']['seed tmt'])

In [418]:
statistics.mode(df5[df5['germination']!='?']['germination'])

In [419]:
statistics.mode(df5[df5['halo']!='?']['halo'])

In [420]:
statistics.mode(df5[df5['marg']!='?']['marg'])

In [421]:
statistics.mode(df5[df5['size']!='?']['size'])

In [422]:
statistics.mode(df5[df5['leaf shred']!='?']['leaf shred'])

In [423]:
statistics.mode(df5[df5['leaf malf']!='?']['leaf malf'])

In [424]:
statistics.mode(df5[df5['leaf mild']!='?']['leaf mild'])

In [425]:
statistics.mode(df5[df5['lodging']!='?']['lodging'])

In [426]:
statistics.mode(df5[df5['fruiting bodies']!='?']['fruiting bodies'])

In [427]:
statistics.mode(df5[df5['fruit pods']!='?']['fruit pods'])

In [428]:
statistics.mode(df5[df5['fruit spots']!='?']['fruit spots'])

In [429]:
statistics.mode(df5[df5['seed']!='?']['seed'])

In [430]:
statistics.mode(df5[df5['mold growth']!='?']['mold growth'])

In [431]:
statistics.mode(df5[df5['seed discolor']!='?']['seed discolor'])

In [432]:
statistics.mode(df5[df5['seed size']!='?']['seed size'])

In [433]:
np.sum(df17=='?')

date             0
plant stand      0
precip           0
temp             0
hail             0
area damage      0
severity         0
plant growth     0
halo             0
marg             0
size             0
leaf mild        0
stem             0
lodging          0
int discolor     0
sclerotia        0
fruit pods       0
fruit spots      0
seed             0
mold growth      0
seed discolor    0
seed size        0
shriveling       0
class            0
dtype: int64

In [434]:
statistics.mode(df5[df5['plant stand']!='?']['plant stand'])

In [435]:
statistics.mode(df5[df5['germination']!='?']['germination'])

HERE WE LOAD THE CSV FILE IN THE DATASET

In [81]:
# Load a CSV file
def load_csv(filename):
	dataset = list()
	with open(filename, 'r') as file:
		csv_reader = reader(file)
		for row in csv_reader:
			if not row:
				continue
			dataset.append(row)
	return dataset

HERE WE DID K-FOLD CROSS VALIDATION SPLITS

In [83]:
# Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
	dataset_split = list()
	dataset_copy = list(dataset)
	fold_size = int(len(dataset) / n_folds)
	for i in range(n_folds):
		fold = list()
		while len(fold) < fold_size:
			index = randrange(len(dataset_copy))
			fold.append(dataset_copy.pop(index))
		dataset_split.append(fold)
	return dataset_split

HERE WE CALCULATED THE ACCURACY SCORE

In [84]:
# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
	correct = 0
	for i in range(len(actual)):
		if actual[i] == predicted[i]:
			correct += 1
	return correct / float(len(actual)) * 100.0

HERE WE CODED URTHER TO GET THE EVALUATION DONE(LIKE-CONFUSION MATRIX,CLASSIFICATION REPORT ETC)

In [259]:
# Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        print(confusion_matrix(actual, predicted))
        print(metrics.classification_report(actual,predicted))
        scores.append(accuracy)
        #metrics.plot_roc_curve(decision_tree, X_test, y_test)
    return scores


In [86]:
# Split a dataset based on an attribute and an attribute value
def test_split(index, value, dataset):
	left, right = list(), list()
	for row in dataset:
		if row[index] < value:
			left.append(row)
		else:
			right.append(row)
	return left, right

HERE WE FORMED THE GINI INDEX

In [87]:
# Calculate the Gini index for a split dataset
def gini_index(groups, class_values):
	gini = 0.0
	for class_value in class_values:
		for group in groups:
			size = len(group)
			if size == 0:
				continue
			proportion = [row[-1] for row in group].count(class_value) / float(size)
			gini += (proportion * (1.0 - proportion))
	return gini

In [88]:
# Select the best split point for a dataset
def get_split(dataset):
	class_values = list(set(row[-1] for row in dataset))
	b_index, b_value, b_score, b_groups = 999, 999, 999, None
	for index in range(len(dataset[0])-1):
		for row in dataset:
			groups = test_split(index, row[index], dataset)
			gini = gini_index(groups, class_values)
			if gini < b_score:
				b_index, b_value, b_score, b_groups = index, row[index], gini, groups
	return {'index':b_index, 'value':b_value, 'groups':b_groups}


In [89]:
# Create a terminal node value
def to_terminal(group):
	outcomes = [row[-1] for row in group]
	return max(set(outcomes), key=outcomes.count)

In [90]:
# Create child splits for a node or make terminal
def split(node, max_depth, min_size, depth):
	left, right = node['groups']
	del(node['groups'])
	# check for a no split
	if not left or not right:
		node['left'] = node['right'] = to_terminal(left + right)
		return
	# check for max depth
	if depth >= max_depth:
		node['left'], node['right'] = to_terminal(left), to_terminal(right)
		return
	# process left child
	if len(left) <= min_size:
		node['left'] = to_terminal(left)
	else:
		node['left'] = get_split(left)
		split(node['left'], max_depth, min_size, depth+1)
	# process right child
	if len(right) <= min_size:
		node['right'] = to_terminal(right)
	else:
		node['right'] = get_split(right)
		split(node['right'], max_depth, min_size, depth+1)


In [91]:
# BuildING a decision tree
def build_tree(train, max_depth, min_size):
	root = get_split(dataset)
	split(root, max_depth, min_size, 1)
	return root

In [92]:
# Make a prediction with a decision tree
def predict(node, row):
	if row[node['index']] < node['value']:
		if isinstance(node['left'], dict):
			return predict(node['left'], row)
		else:
			return node['left']
	else:
		if isinstance(node['right'], dict):
			return predict(node['right'], row)
		else:
			return node['right']

In [93]:
# Classification and Regression Tree Algorithm
def decision_tree(train, test, max_depth, min_size):
    tree = build_tree(train, max_depth, min_size)
    predictions = list()
    for row in test:
      prediction = predict(tree, row)
      predictions.append(prediction)
    #print(predictions)
    return(predictions)

RUNNING A LOOP FOR CHECKING PERFORMANCE IN DIFFERENT K-VALUES

In [437]:
# load and prepare data
filename = 'SOYABEAN_new.csv'
dataset = load_csv(filename)
for i in range(1,20):
 n_folds = i
 max_depth = 10
 min_size = 10
 scores = evaluate_algorithm(dataset, decision_tree, n_folds, max_depth, min_size)
 print('Scores: %s' % scores)
 print('Mean Accuracy: %.3f%%' % (sum(scores)/float(len(scores))))

['7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '6.00', '7.00', '7.00', '7.00', '4.00', '0.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '1.00', '7.00', '7.00', '15.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '4.00', '7.00', '5.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00', '7.00', '1.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00'

C:\Users\Utkarsh\Downloads\anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


['7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '4.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '0.00', '7.00', '15.00', '4.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00', '4.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '5.00', '7.0

['7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '0.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '4.00', '4.00', '7.00', '7.00', '6.00', '7.00', '1.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '5.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '4.00', '4.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0  

['7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '4.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '4.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '6.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  

['7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '4.00', '6.00', '6.00', '7.00', '4.00', '7.00', '7.00', '7.00', '5.00', '1.00', '7.00', '4.00', '4.00', '7.00', '4.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '5.00']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 9 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 

['7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '0.00', '7.00', '7.00', '7.00', '7.00']
[[1 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 9 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]]
             precision    reca

['7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '1.00', '7.00', '4.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0

['7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '4.00', '7.00', '7.00', '1.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '15.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00']
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  

['7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '6.00', '1.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '1.00', '7.00', '1.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         2
       1.00       1.00      1.00      1.00         4
      10.00       0.00      0.00      

['7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00', '12.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
       1.00       1.00      1.00      1.00         1
      11.00       0.00      0.00      0.00         2
      12.00       1.00      1.00      1.00         2
      13.00       0.00      0.00      0.00         6
      14.00       0.00      

['7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
       1.00       1.00      1.00      1.00         1
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         5
      13.00       0.00    

['4.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00']
[[ 2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]]
             precision    recall  f1-score   support

       1.00       1.00      1.00      1.00         2
      10.00       0.00      0.00      0.00         2
      11.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         1
      14.00       0.00  

['5.00', '1.00', '7.00', '12.00', '7.00', '7.00', '12.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 3]
 [0 0 0 2 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 3]]
             precision    recall  f1-score   support

       1.00       1.00      1.00      1.00         2
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         3
      12.00       1.00      0.67      0.80         3
      13.00       0.00      0.00      0.00         3
      14.00       0.00      0.00      0.00         5
      1

['7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '15.00', '7.00', '7.00', '7.00', '7.00', '5.00', '6.00', '7.00', '12.00', '5.00', '1.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
       1.00       1.00      1.00      1.00         1
      12.00       1.00      1.00      1.00         1
      13.00       0.00      0.00      0.00         3
      14.00       0.00      0.00      0.00         4
      15.00       1.00      1.00      1.00         1
      18.00       0.00      0.0

['7.00', '7.00', '7.00', '7.00', '12.00', '6.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '4.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00']
[[0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]]
             precision    recall  f1-score   support

      11.00       0.00      0.00      0.00         2
      12.00       1.00      1.00      1.00         1
      13.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         4
      15.00       0.00      0.00      0.00         2
      18.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00      

['7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '12.00', '7.00']
[[0 0 0 0 0 0 0 0 0 2 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 3 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         2
       1.00       1.00      1.00      1.00         1
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         1
      12.00       1.00      0.50      0.67         2
      13.00       0.00      0.00      0.00         4
      14.00       0.00      0.00      0.00         3
      16.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00  

['6.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 2 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 0 2 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         2
       1.00       1.00      1.00      1.00         1
      11.00       0.00      0.00      0.00         3
      13.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         2
      18.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         2
       3.00       0.00      0.00      0.00         2
       4.00 

['7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '4.00', '6.00', '4.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

      11.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         4
      15.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         2
       3.00       0.00      0.00      0.00         6
       4.00       1.00      1.00      1.00         3
       5.00       1.00      1.00      1.00         1
       6.00       1.00      1.00      1.00         2
       7

['7.00', '7.00', '4.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         3
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         5
      15.00       0.00      0.00      0.00         1
      16.00       0.00  

['7.00', '7.00', '4.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '15.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 2 0]]
             precision    recall  f1-score   support

      10.00       0.00      0.00      0.00         2
      11.00       0.00      0.00      0.00         2
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         2
      15.00       1.00      1.00      1.00         1
       3.00       0.00      0.00      0.00         4
       4.00       1.00      1.00      1.00         2
       5.00       1.00      1.00      1.00         1
       7.00       0.18      1.00      0.30         3
       8.00       0.00      0.00      0.00         2

avg / total   

C:\Users\Utkarsh\Downloads\anaconda\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


['4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '12.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00']
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]]
             precision    recall  f1-score   support

       1.00       1.00      1.00      1.00         1
      11.00       0.00      0.00      0.00         4
      12.00       1.00      1.00      1.00         1
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         3
      18.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         1
       4.00       1.00      1.00      1.00         2
       5.00       1.00      1.00   

['7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         3
      14.00       0.00      0.00      0.00         2
      16.00       0.00      0.00      0.00         1
      18.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         3
       6.00       1.00      1.00    

['7.00', '7.00', '7.00', '0.00', '7.00', '5.00', '6.00', '7.00', '7.00', '7.00', '12.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00']
[[1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 2]]
             precision    recall  f1-score   support

       0.00       1.00      1.00      1.00         1
      10.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         1
      12.00       1.00      0.50      0.67         2
      13.00       0.00      0.00      0.00         5
      14.00       0.00      0.00      0.00         2
       3.00       0.00      0.00      0.00         2
       4.00       1.00      1.00      1.00         1
       5.00       1.00      1.00      1.00         1
       6.00       1.00      1.00      1

['7.00', '7.00', '1.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 2 0]]
             precision    recall  f1-score   support

       1.00       1.00      1.00      1.00         1
      12.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         5
      18.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         3
       6.00       1.00      1.00      1.00         1
       7.00       0.18      1.00      0.30         3
       9.00       0.00      0.00      0.00         2

avg / total       0.13      0.26      0.15        19

['5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '1.00', '7.00', '4.00'

['5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '6.00']
[[0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

      11.00       0.00      0.00      0.00         1
      12.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         3
      15.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         2
       3.00       0.00      0.00      0.00         4
       4.00       1.00      1.00      1.00         2
       5.00       1.00      1.00      1.00         1
       6.00       1.00      1.00      1.00         2
       7.00       0.00      0.00      0.00      

['7.00', '7.00', '7.00', '7.00', '7.00', '6.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '15.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 4 0]
 [0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 2 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

      11.00       0.00      0.00      0.00         2
      13.00       0.00      0.00      0.00         4
      15.00       1.00      0.50      0.67         2
      17.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         2
       6.00       1.00      1.00      1.00         1
       7.00       0.31      1.00      0.48         5
       8.00       0.00      0.00      0.00         1

avg / total       0.25      0.39      0.26        18

['12.00', '7.00', '5.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 2 

['4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00']
[[0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
      11.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         5
      15.00       0.00      0.00      0.00         1
      16.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         1
       4.00       1.00      1.00      1.00         1
       7.00       0.12      1.00      0.22         2
   

['7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00']
[[0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
      10.00       0.00      0.00      0.00         2
      11.00       0.00      0.00      0.00         1
      13.00       0.00      0.00      0.00         2
      14.00       0.00      0.00      0.00         1
      15.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         2
       

['7.00', '7.00', '4.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '1.00', '7.00']
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 4]]
             precision    recall  f1-score   support

       1.00       1.00      1.00      1.00         1
      10.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         1
      16.00       0.00      0.00      0.00         1
       2.00       0.00      0.00      0.00         2
       3.00       0.00      0.00      0.00         3
       4.00       1.00      1.00      1.00         3
       7.00       0.33      1.00      0.50         4

avg / total       0.33      0.50      0.38        16

['7.00', '7.00', '7.00', '7.00', '7.00', '5.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '5.00']
[[0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 3 0 0]
 [0 0 

['7.00', '7.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00']
[[0 0 0 0 0 1 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 3 0]
 [0 0 0 0 0 1 0]]
             precision    recall  f1-score   support

       0.00       0.00      0.00      0.00         1
      14.00       0.00      0.00      0.00         4
      16.00       0.00      0.00      0.00         1
       3.00       0.00      0.00      0.00         4
       4.00       1.00      1.00      1.00         2
       7.00       0.21      1.00      0.35         3
       9.00       0.00      0.00      0.00         1

avg / total       0.17      0.31      0.19        16

['7.00', '7.00', '7.00', '1.00', '7.00', '7.00', '4.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '7.00', '4.00']
[[1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 2 

In [145]:
dataset[0][0]=dataset[0][0].split('¿')[1]

NEW DATAFRAME(JUST ANOTHER LOOK)

In [185]:
df1.corr()

date  plant stand    precip      temp      hail  \
date           1.000000    -0.333507 -0.081855  0.279563 -0.036691   
plant stand   -0.333507     1.000000  0.113762 -0.062045 -0.105338   
precip        -0.081855     0.113762  1.000000  0.006620 -0.176256   
temp           0.279563    -0.062045  0.006620  1.000000  0.027811   
hail          -0.036691    -0.105338 -0.176256  0.027811  1.000000   
area damage    0.126436    -0.150526 -0.098964  0.193786  0.017718   
severity      -0.429178     0.263431  0.081989 -0.148230 -0.111815   
plant growth  -0.360708     0.248589 -0.055290 -0.170282  0.096341   
halo           0.150219    -0.184013  0.247288  0.220359 -0.081123   
marg          -0.144255     0.193328 -0.241285 -0.234475  0.084112   
size          -0.112386     0.209187 -0.173353 -0.124157 -0.035225   
leaf mild     -0.009864     0.086043 -0.044733 -0.159812  0.122033   
stem           0.022154     0.094566 -0.046487 -0.023562 -0.135046   
lodging        0.116715    -0.034800 -0.151100 -0.119220  0.353427   
int discolor   0.178835    -0.204227 -0.676028  0.049144  0.117301   
sclerotia      0.135927    -0.166938 -0.415232  0.141158  0.153524   
fruit pods    -0.398658     0.419391  0.250555 -0.158014 -0.147251   
fruit spots   -0.148562     0.264710 -0.056879 -0.099163 -0.010285   
seed           0.157522    -0.163364  0.183587 -0.063755  0.133809   
mold growth    0.078704    -0.005092  0.147787  0.001088  0.097156   
seed discolor  0.159190    -0.176153  0.086809  0.026555  0.176541   
seed size      0.118302    -0.077473  0.114270  0.066783 -0.055098   
shriveling     0.218298     0.018912  0.093998  0.142244 -0.071329   
class          0.319357    -0.178437  0.298885  0.251860 -0.129062   

               area damage  severity  plant growth      halo      marg  \
date              0.126436 -0.429178     -0.360708  0.150219 -0.144255   
plant stand      -0.150526  0.263431      0.248589 -0.184013  0.193328   
precip           -0.098964  0.081989     -0.055290  0.247288 -0.241285   
temp              0.193786 -0.148230     -0.170282  0.220359 -0.234475   
hail              0.017718 -0.111815      0.096341 -0.081123  0.084112   
area damage       1.000000 -0.127289     -0.228482  0.223084 -0.198832   
severity         -0.127289  1.000000      0.558935 -0.437267  0.453634   
plant growth     -0.228482  0.558935      1.000000 -0.563278  0.598218   
halo              0.223084 -0.437267     -0.563278  1.000000 -0.972406   
marg             -0.198832  0.453634      0.598218 -0.972406  1.000000   
size             -0.117485  0.479347      0.533553 -0.813365  0.840995   
leaf mild        -0.084721 -0.057451     -0.178631 -0.051216 -0.045563   
stem             -0.051854  0.434313      0.461897 -0.523053  0.560706   
lodging           0.008059  0.001090      0.231495 -0.178342  0.183278   
int discolor      0.177173  0.064650      0.235404 -0.298955  0.304274   
sclerotia         0.148043  0.031546      0.256362 -0.216098  0.218883   
fruit pods       -0.228007  0.557980      0.619372 -0.450447  0.481260   
fruit spots      -0.223785  0.588042      0.770932 -0.645732  0.659546   
seed              0.022547 -0.187211     -0.079085 -0.005881 -0.027319   
mold growth       0.064411 -0.023896     -0.125669 -0.045497 -0.001707   
seed discolor     0.066312 -0.235576     -0.083318  0.015936  0.004410   
seed size         0.084852 -0.015987     -0.003562  0.005777 -0.009236   
shriveling        0.107457 -0.025987     -0.136870 -0.062372  0.068055   
class             0.145109 -0.561257     -0.530323  0.662340 -0.630011   

                 ...     int discolor  sclerotia  fruit pods  fruit spots  \
date             ...         0.178835   0.135927   -0.398658    -0.148562   
plant stand      ...        -0.204227  -0.166938    0.419391     0.264710   
precip           ...        -0.676028  -0.415232    0.250555    -0.056879   
temp             ...         0.049144   0.141158   -0.158014    -0.099163   
hail             ...         0.1

ANOTHER APPROACH USING LIBRARIES

In [326]:
 from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_curve, auc
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import label_binarize
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt


C:\Users\Utkarsh\Downloads\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [272]:
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)

In [275]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [276]:
classifier.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [277]:
y_pred=classifier.predict(x_test)
y_pred

array([ 3., 13., 16.,  7., 11.,  7., 14.,  2.,  2.,  3., 14.,  5., 13.,
        3.,  3., 12., 13., 13., 13., 13., 11.,  1.,  4.,  3., 13.,  1.,
        4., 14.,  8.,  4.,  7., 13.,  7., 13., 14.,  9., 11., 13.,  7.,
       14.,  3.,  3.,  9.,  1.,  7.,  0.,  7.,  9.,  7., 13., 11., 10.,
       13.,  0.,  3.,  6., 14.,  3.,  6.,  2.,  2., 14.])

In [287]:
#accuracy = accuracy_metric(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print('accuracy = ',accuracy_score(y_test, y_pred, normalize=False))

[[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 12  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00         2
        1.0       1.00      1.00      1.00         3
        2.0       0.50 

In [314]:
from sklearn.metrics import roc_curve, auc
from sklearn import svm

In [295]:
import numpy as np
from sklearn import metrics
y_pred=classifier.predict_proba(x_test)[:,1]

HERE WE'VE FOUND THE TPR(TRUE POSITIVE RATE) AND FPR(FALSE POSITIVE RATE)

In [411]:
for i in range(19):
    fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=2)
    print('fpr = ',fpr)
    print('\n')
    print('tpr = ',tpr)

fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [0.         0.05084746 1.        ]


tpr =  [0. 0. 1.]
fpr =  [

THANKS ALOT FOR THIS COURSE, CS40003!! REALLY ENJOYED IT.